builds:
  - binary: flow
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  mode: keep-existing
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: flow
    repository:
      owner: edens-angel
      name: flow-cli
    commit_author:
      name: edens-angel
    homepage: https://github.com/Edens-Angel/flow-cli
    description: "Devops CLI to handle basic devops tasks"
    test: system "flow ip"

checksum:
  name_template: "checksums.sha256"
